---
- hosts: all
  tasks:
    - name: build container image
      docker_image:
        name: hellopython3
        build:
          pull: yes
          path: Dockerfile
        source: build
        state: present